### ISSUE TITLE
NPM install issue

### ISSUE THREAD

**Issue by Noitidart** [mxck/react-native-material-menu#7] opened 2017-12-01 18:57 UTC
For some reason, I cannot install (`npm i`) other packages while this package is installed. I get the error below. I have to first `npm un react-native-material-menu` and then install the other package then I can install this back. Is this just me?

### Environment

Environment:
OS: Windows 10
Node: 8.4.0
Yarn: 0.19.1
npm: 5.4.2
Watchman: Not Found
Xcode: N/A
Android Studio: Version 2.3.0.0 AI-162.3764568

Packages:
react: 16.0.0
react-native: 0.47.1

### Error

> PS C:\Users\Mercurius\Documents\GitHub\trustedplatform_android> npm i react-native-carousel-pager
npm ERR! path C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\react-native-material-menu
npm ERR! code EISGIT
npm ERR! git C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\react-native-material-menu: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\react-native-material-menu
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

> npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mercurius\AppData\Roaming\npm-cache\_logs\2017-12-01T18_53_56_927Z-debug.log

**Comment by mxck** [comment] 2017-12-02 12:42
@Noitidart can you fully remove node_modules folder?
`rm -rf node_modules`
then run
`npm install` or `yarn`

**Comment by Noitidart** [comment] 2017-12-02 14:48
Thanks mxck! I will try that on Monday please :)

**Comment by Noitidart** [comment] 2017-12-06 21:20
Thanks so much @mxck for leaving this open for me. I haven't been able to fix this. I'm not sure why. I'll close this out. It seems something specific to me. Thanks very much again. I'll update you when I find a fix. :)

**Comment by Noitidart** [comment] 2017-12-07 00:47
Oh just an update to the stuff I tried:

* the `rm -rf node_modules` then `npm i` 
* created a new react native project `react-native init` and tried it here

Same results in both. Will keep you updated.

**Comment by Noitidart** [comment] 2018-01-17 17:40
@mxck Im still having this problem even in new project.

I was wondering what was the equivalent of `rm -rf node_modules` in windows, do you know please?

**Comment by kcbar** [comment] 2018-01-24 22:03
I had this issue. I switched to using yarn instead of npm and it doesn't happen anymore.

**Comment by Noitidart** [comment] 2018-01-24 22:15
@kcbar that's an interesting note. It would be nice to find the root cause though.

**Comment by mxck** [comment] 2018-01-25 03:14
Ok, I reopen ticket and test with NPM

**Comment by Noitidart** [comment] 2018-01-25 04:00
Thanks @mxck!

**Comment by mxck** [comment] 2018-01-28 13:44
@Noitidart I don't have any errors at my Mac with npm.
```
❯ npm --version
5.6.0
```
What version you using?

**Comment by Noitidart** [comment] 2018-01-28 18:45
@mxck  I am on windows, also 5.6.0

**Comment by DevAlien** [comment] 2018-01-31 16:38
@mxck I'm on mac, it happens when I run npm install a second time, the first time goes well.

I think the issue is that in the package we get from npm there's a .git folder, you should not package that one.

Removing the .git directory inside node_modules/react-native-material-menu works

`rm -rf node_modules/react-native-material-menu/.git`

**Comment by mxck** [comment] 2018-01-31 17:38
Hm. Ok I check it later. Thanks!
ср, 31 янв. 2018 г. в 23:38, Gonçalo Margalho <notifications@github.com>:

**Comment by DevAlien** [comment] 2018-01-31 17:48
Thanks to you man, if you solve it would be very good for us :)

**Comment by mxck** [comment] 2018-02-01 04:08
```
By default, the following paths and files are ignored, so there's no need to add them to .npmignore explicitly:

.*.swp
._*
.DS_Store
.git
.hg
.npmrc
.lock-wscript
.svn
.wafpickle-*
config.gypi
CVS
npm-debug.log
```
Hmm. Something goes wrong. :)

**Comment by mxck** [comment] 2018-02-01 04:28
Fixed in c398fc497150809

**Closed by mxck** 2018-02-01 04:28 UTC

**Comment by mxck** [comment] 2018-02-01 04:30
NPM have a bug with it https://github.com/npm/npm/issues/19073
Publish last version with yarn :)

**Comment by Noitidart** [comment] 2018-02-01 18:27
Woohoo it works!!! Thanks all!!
